name: Caching Primes

on: [pull_request,push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: prime-numbers
        key: primes

    - name: Use Prime Numbers
      run: cat prime-numbers
